# Generated by Django 5.0 on 2023-12-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_rename_todolist_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
