# Generated by Django 5.0 on 2023-12-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_list_date_list_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
