# Generated by Django 5.0 on 2023-12-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_list_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='background_color',
        ),
    ]
