# Generated by Django 5.0 on 2023-12-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_remove_list_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='color',
            field=models.CharField(default='#faf78e', max_length=7),
        ),
    ]
