# Generated by Django 5.0 on 2023-12-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_list_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
