# Generated by Django 5.0 on 2023-12-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0009_alter_list_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='color',
        ),
    ]
