# Generated by Django 5.0 on 2023-12-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0011_list_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='color',
            field=models.CharField(default='pastel-yellow', max_length=20),
        ),
    ]
