# Generated by Django 5.0 on 2023-12-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0013_alter_list_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='color',
            field=models.CharField(default='#f7e7b4', max_length=20),
        ),
    ]
