# Generated by Django 5.0 on 2023-12-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0014_alter_list_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='color',
            field=models.CharField(default='pastel-brown', max_length=20),
        ),
    ]
